### ISSUE TITLE
unable to find aws-auth-cn.yaml file to update

### ISSUE THREAD

**Issue by sachin76-k** [aws-samples/cfn-nodegroup-for-multus-cni#2]
hi Can you please let me know where to find file aws-auth-cn.yaml? 
I am unable to find one and also unable to get one from "kubectl describe configmap -n kube-system" command if its  config map file you are refereeing to

**Comment by jungy-aws** [comment]
Please refer to
https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html

There is a guide with for the download of it.
curl -o aws-auth-cm.yaml https://s3.us-west-2.amazonaws.com/amazon-eks/cloudformation/2020-10-29/aws-auth-cm.yaml
