### ISSUE TITLE
Nodegroup not getting attached

### ISSUE THREAD

**Issue by sachin76-k** [aws-samples/cfn-nodegroup-for-multus-cni#3]
My nodegroup is not getting attached to cluster , Any debugging tips. I have added Node ARN to aws-auth-cm.yaml file and applied it.

**Comment by jungy-aws** [comment]
For debugging tip, you can access to worker node host and check kubelet log file from /var/messages (also you might have to check kubelet status). In many cases, it happens, if worker node has no access to EKS (if EKS is configure to allow public access, then workernode needs to access through NAT-GW and/or IGW). Those things can be debugged through kubelet log file.
