### ISSUE TITLE
Segregate Multus Network IPs consumed by WorkerNodes and Application PODs

### ISSUE THREAD

**Issue by ggkunka** [aws-samples/cfn-nodegroup-for-multus-cni#4]
Hello All,

Is there a way to segregate the IP pool between the EC2 worker node hosts and multus application pods. 
For Ex: 10.10.35.0/24 is configured as a multus network. 
Now If I spawn 5 worker nodes, the nodes consume 5 IPs randomly between 10.10.35.5 and 10.10.35.254. Is there a way to control this IP allocation as it sometimes disrupts application pods IP planning?

Thanks,
Jayaprakash

**Comment by jungy-aws** [comment]
Hi,
It's not in the scope of this repo, but in practice, we can think about creating dummy-interface in the subnet (before creating worker node group). To the dummy interface, you can (pre-)bind IP addresses to be used for application as secondary IPs of interface (please keep in mind, you have to turn on 'reassign allowed". We can also think about creating lambda and small DB to manage these IPs using this dummy-interface to preserve IP addresses for multus application but it would be beyond the scope of this repo.
